#!/bin/bash

# PostgreSQL データベースとユーザーのセットアップスクリプト
# 注: このスクリプトはsudo権限が必要です

echo "PostgreSQL セットアップスクリプト"
echo "================================"
echo ""
echo "このスクリプトを実行するには、以下のコマンドを手動で実行してください:"
echo ""
echo "1. PostgreSQLユーザーとして接続:"
echo "   sudo -u postgres psql"
echo ""
echo "2. 以下のSQLコマンドを実行:"
echo "   CREATE USER lawfinder WITH PASSWORD 'lawfinder123';"
echo "   CREATE DATABASE lawfinder OWNER lawfinder;"
echo "   GRANT ALL PRIVILEGES ON DATABASE lawfinder TO lawfinder;"
echo "   \\q"
echo ""
echo "3. 接続テスト:"
echo "   psql -U lawfinder -h localhost -d lawfinder"
echo ""
echo "4. .envファイルを更新:"
echo "   DATABASE_URL=postgresql://lawfinder:lawfinder123@localhost:5432/lawfinder"
echo ""

# 代替案: peer認証を使用する場合
echo "代替案: peer認証を使用する場合"
echo "==============================="
echo ""
echo "1. システムユーザー 'lawfinder' を作成:"
echo "   sudo adduser lawfinder"
echo ""
echo "2. PostgreSQLユーザーを作成:"
echo "   sudo -u postgres createuser lawfinder"
echo ""
echo "3. データベースを作成:"
echo "   sudo -u postgres createdb -O lawfinder lawfinder"
echo ""
echo "4. .envファイルを更新:"
echo "   DATABASE_URL=postgresql://lawfinder@localhost/lawfinder"
echo ""